# Generated by Django 2.2.5 on 2019-09-18 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_articlecategory_articlecategoryorderable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='basepage',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='An image for including on other pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.CustomImage'),
        ),
    ]
