# Generated by Django 2.2.5 on 2019-09-18 04:39

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190917_2339'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='people.Person'),
        ),
        migrations.AddField(
            model_name='author',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='core.BasePage'),
        ),
    ]
