# Generated by Django 2.2.5 on 2019-09-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190918_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
