# Generated by Django 2.2.5 on 2019-09-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='fa_icon',
            field=models.CharField(blank=True, max_length=25, verbose_name='Font Awesome icon'),
        ),
    ]
