# Generated by Django 2.2.5 on 2019-09-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_auto_20190919_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['sort_order']},
        ),
        migrations.DeleteModel(
            name='SubItem',
        ),
    ]
